"use client";
import { useEffect, useState } from "react";
import { BookOpen, Plus, Trash2, Eye, Loader2, Brain, Building2, CheckSquare, Square, Download } from "lucide-react";
import { formatDate, getStatusColor } from "@/lib/utils";
import toast from "react-hot-toast";
import Link from "next/link";

interface Report {
  id: string;
  title: string;
  reportType: string;
  companies: string[] | null;
  status: string;
  executiveSummary: string | null;
  fullReportContent: string | null;
  createdAt: string;
}

interface Company {
  id: string;
  name: string;
  ticker: string | null;
}

interface Session {
  id: string;
  name: string;
}

export default function ReportsPage() {
  const [reports, setReports] = useState<Report[]>([]);
  const [companies, setCompanies] = useState<Company[]>([]);
  const [sessions, setSessions] = useState<Session[]>([]);
  const [loading, setLoading] = useState(true);
  const [showForm, setShowForm] = useState(false);
  const [generating, setGenerating] = useState(false);
  const [form, setForm] = useState({ title: "", sessionId: "", companyIds: [] as string[], additionalContext: "" });

  async function fetchAll() {
    setLoading(true);
    const [rRes, cRes, sRes] = await Promise.all([
      fetch("/api/reports"),
      fetch("/api/companies"),
      fetch("/api/sessions"),
    ]);
    if (rRes.ok) setReports((await rRes.json()).reports || []);
    if (cRes.ok) setCompanies((await cRes.json()).companies || []);
    if (sRes.ok) setSessions((await sRes.json()).sessions || []);
    setLoading(false);
  }

  useEffect(() => {
    const timer = window.setTimeout(() => void fetchAll(), 0);
    return () => window.clearTimeout(timer);
  }, []);

  function toggleCompany(id: string) {
    setForm((prev) => ({
      ...prev,
      companyIds: prev.companyIds.includes(id)
        ? prev.companyIds.filter((x) => x !== id)
        : [...prev.companyIds, id],
    }));
  }

  async function generateReport(e: React.FormEvent) {
    e.preventDefault();
    if (form.companyIds.length === 0) {
      toast.error("Select at least one company");
      return;
    }
    setGenerating(true);
    try {
      const res = await fetch("/api/reports", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(form),
      });
      if (res.ok) {
        toast.success("Report generation started!");
        setShowForm(false);
        await fetchAll();
      } else {
        const d = await res.json();
        toast.error(d.error || "Failed");
      }
    } finally {
      setGenerating(false);
    }
  }

  async function deleteReport(id: string) {
    if (!confirm("Delete this report?")) return;
    await fetch(`/api/reports/${id}`, { method: "DELETE" });
    toast.success("Report deleted");
    setReports(reports.filter((r) => r.id !== id));
  }

  function downloadReport(report: Report) {
    // Client-side text download
    const content = `FINANCIAL ANALYSIS REPORT
Generated by FinResearch AI

Title: ${report.title}
Generated: ${formatDate(report.createdAt)}
Companies: ${report.companies?.join(", ") || "N/A"}
Type: ${report.reportType}

EXECUTIVE SUMMARY
${report.fullReportContent || report.executiveSummary || "Report content is still being generated."}

---
Generated by FinResearch AI Multi-Agent System
`;
    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${report.title.replace(/[^a-z0-9]/gi, "_")}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  }

  if (loading) return <div className="flex items-center justify-center h-64"><Loader2 className="w-6 h-6 animate-spin text-blue-500" /></div>;

  return (
    <div className="p-6 space-y-6 animate-fade-in">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-slate-900">Analysis Reports</h1>
          <p className="text-slate-500 text-sm mt-1">AI-generated analyst-style financial research reports</p>
        </div>
        <button
          onClick={() => setShowForm(true)}
          className="flex items-center gap-2 px-4 py-2 bg-blue-600 text-white rounded-xl text-sm font-semibold hover:bg-blue-700 transition-colors shadow-lg shadow-blue-500/25"
        >
          <Plus className="w-4 h-4" /> Generate Report
        </button>
      </div>

      {/* Generate Report Modal */}
      {showForm && (
        <div className="fixed inset-0 bg-black/50 z-50 flex items-center justify-center p-4">
          <div className="bg-white rounded-2xl shadow-2xl w-full max-w-lg p-6 animate-fade-in max-h-[90vh] overflow-y-auto">
            <div className="flex items-center gap-2 mb-4">
              <Brain className="w-5 h-5 text-blue-600" />
              <h2 className="text-lg font-bold text-slate-900">Generate Analysis Report</h2>
            </div>

            <form onSubmit={generateReport} className="space-y-4">
              <div>
                <label className="block text-xs font-medium text-slate-600 mb-1">Report Title (optional)</label>
                <input
                  placeholder="Auto-generated if empty"
                  value={form.title}
                  onChange={(e) => setForm({ ...form, title: e.target.value })}
                  className="w-full px-3 py-2 border border-slate-200 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
                />
              </div>

              <div>
                <label className="block text-xs font-medium text-slate-600 mb-2">
                  Select Companies * ({form.companyIds.length} selected)
                </label>
                <div className="grid grid-cols-2 gap-2">
                  {companies.map((co) => (
                    <button
                      key={co.id}
                      type="button"
                      onClick={() => toggleCompany(co.id)}
                      className={`flex items-center gap-2 p-2.5 rounded-lg border text-left text-sm transition-all ${form.companyIds.includes(co.id) ? "border-blue-500 bg-blue-50 text-blue-900" : "border-slate-200 hover:border-blue-200"}`}
                    >
                      {form.companyIds.includes(co.id) ? (
                        <CheckSquare className="w-4 h-4 text-blue-600 shrink-0" />
                      ) : (
                        <Square className="w-4 h-4 text-slate-300 shrink-0" />
                      )}
                      <div>
                        <div className="font-medium text-xs">{co.ticker || co.name}</div>
                        <div className="text-xs text-slate-400 truncate">{co.name}</div>
                      </div>
                    </button>
                  ))}
                </div>
              </div>

              <div>
                <label className="block text-xs font-medium text-slate-600 mb-1">Research Session (optional)</label>
                <select
                  value={form.sessionId}
                  onChange={(e) => setForm({ ...form, sessionId: e.target.value })}
                  className="w-full px-3 py-2 border border-slate-200 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
                >
                  <option value="">No session</option>
                  {sessions.map((s) => <option key={s.id} value={s.id}>{s.name}</option>)}
                </select>
              </div>

              <div>
                <label className="block text-xs font-medium text-slate-600 mb-1">Additional Context</label>
                <textarea
                  rows={2}
                  placeholder="Any specific focus areas or questions..."
                  value={form.additionalContext}
                  onChange={(e) => setForm({ ...form, additionalContext: e.target.value })}
                  className="w-full px-3 py-2 border border-slate-200 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-blue-500 resize-none"
                />
              </div>

              <div className="bg-blue-50 rounded-lg p-3 text-xs text-blue-700">
                <strong>Report Agent</strong> will compile: executive summary, financial analysis, risk assessment, and investment recommendations.
              </div>

              <div className="flex gap-3">
                <button type="button" onClick={() => setShowForm(false)} className="flex-1 py-2.5 border border-slate-200 text-slate-600 rounded-xl text-sm hover:bg-slate-50">Cancel</button>
                <button type="submit" disabled={generating} className="flex-1 py-2.5 bg-blue-600 text-white rounded-xl text-sm font-semibold hover:bg-blue-700 disabled:opacity-60 flex items-center justify-center gap-2">
                  {generating && <Loader2 className="w-4 h-4 animate-spin" />}
                  {generating ? "Generating..." : "Generate Report"}
                </button>
              </div>
            </form>
          </div>
        </div>
      )}

      {/* Reports List */}
      {reports.length === 0 ? (
        <div className="text-center py-20 bg-white rounded-2xl border border-slate-200">
          <BookOpen className="w-16 h-16 text-slate-200 mx-auto mb-4" />
          <h3 className="text-lg font-semibold text-slate-700 mb-2">No Reports Yet</h3>
          <p className="text-slate-400 text-sm mb-4">Generate your first AI-powered financial analysis report</p>
          <button onClick={() => setShowForm(true)} className="px-4 py-2 bg-blue-600 text-white rounded-xl text-sm font-semibold hover:bg-blue-700">
            Generate Report
          </button>
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {reports.map((report) => (
            <div key={report.id} className="bg-white rounded-xl border border-slate-200 p-5 hover:shadow-md transition-all hover:border-blue-200">
              <div className="flex items-start justify-between mb-3">
                <div className="w-10 h-10 bg-violet-100 rounded-xl flex items-center justify-center shrink-0">
                  <BookOpen className="w-5 h-5 text-violet-600" />
                </div>
                <div className="flex items-center gap-2">
                  <span className={`text-xs px-2 py-0.5 rounded-full font-medium ${getStatusColor(report.status)}`}>
                    {report.status}
                  </span>
                  <button onClick={() => downloadReport(report)} className="p-1.5 text-slate-400 hover:text-blue-600 transition-colors">
                    <Download className="w-3.5 h-3.5" />
                  </button>
                  <button onClick={() => deleteReport(report.id)} className="p-1.5 text-slate-400 hover:text-red-500 transition-colors">
                    <Trash2 className="w-3.5 h-3.5" />
                  </button>
                </div>
              </div>

              <Link href={`/dashboard/reports/${report.id}`}>
                <h3 className="font-semibold text-slate-900 mb-2 hover:text-blue-600 transition-colors">{report.title}</h3>
              </Link>

              {report.companies && report.companies.length > 0 && (
                <div className="flex items-center gap-1.5 mb-2 flex-wrap">
                  <Building2 className="w-3.5 h-3.5 text-slate-400 shrink-0" />
                  {report.companies.map((c) => (
                    <span key={c} className="text-xs bg-slate-100 text-slate-600 px-2 py-0.5 rounded-full">{c}</span>
                  ))}
                </div>
              )}

              {report.executiveSummary && (
                <p className="text-xs text-slate-500 mb-3 line-clamp-3">{report.executiveSummary}</p>
              )}

              <div className="flex items-center justify-between mt-3 pt-3 border-t border-slate-100 text-xs text-slate-400">
                <span>{formatDate(report.createdAt)}</span>
                <Link href={`/dashboard/reports/${report.id}`} className="flex items-center gap-1 text-blue-600 hover:underline font-medium">
                  <Eye className="w-3 h-3" /> View Report
                </Link>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
