import test from "node:test";
import assert from "node:assert/strict";
import {
  CHAT_MODEL_FALLBACKS,
  DEFAULT_LLM_BASE_URL,
  buildModelCandidates,
  describeAiUnavailable,
  describeNarrativeFallbackReason,
  getAiStatus,
  getEmbeddingConfig,
  getLlmBaseUrl,
  isEmbeddingConfigured,
  isLlmConfigured,
  recordAiFailure,
  recordAiSuccess,
} from "./aiStatus";
import { parseJsonResponse } from "./llmClient";

/** Run a callback with a mutated environment, restoring it afterwards. */
function withEnv(vars: Record<string, string | undefined>, run: () => void) {
  const original: Record<string, string | undefined> = {};
  for (const key of Object.keys(vars)) original[key] = process.env[key];
  try {
    for (const [key, value] of Object.entries(vars)) {
      if (value === undefined) delete process.env[key];
      else process.env[key] = value;
    }
    run();
  } finally {
    for (const [key, value] of Object.entries(original)) {
      if (value === undefined) delete process.env[key];
      else process.env[key] = value;
    }
  }
}

test("Groq is the default provider and needs no configuration to know its endpoint", () => {
  withEnv({ LLM_BASE_URL: undefined, GROQ_API_KEY: "gsk_test_key", LLM_API_KEY: undefined }, () => {
    assert.equal(getLlmBaseUrl(), DEFAULT_LLM_BASE_URL);
    assert.match(getLlmBaseUrl(), /api\.groq\.com\/openai\/v1$/);
    assert.equal(isLlmConfigured(), true);
  });
});

test("LLM_API_KEY works as a generic alias so other providers can be swapped in", () => {
  withEnv({ GROQ_API_KEY: undefined, LLM_API_KEY: "sk-other-provider" }, () => {
    assert.equal(isLlmConfigured(), true);
  });
});

test("model candidates keep the configured model first and never duplicate entries", () => {
  const candidates = buildModelCandidates("openai/gpt-oss-120b");
  assert.equal(candidates[0], "openai/gpt-oss-120b");
  assert.equal(candidates.length, new Set(candidates).size, "candidates must be unique");
  assert.ok(candidates.length > 1, "a fallback must always be available");
});

test("a decommissioned model id still has known-good Groq fallbacks after it", () => {
  const candidates = buildModelCandidates("mixtral-8x7b-32768");
  assert.equal(candidates[0], "mixtral-8x7b-32768");
  assert.ok(candidates.includes(CHAT_MODEL_FALLBACKS[0]));
  assert.ok(candidates.includes("openai/gpt-oss-120b"));
});

test("placeholder API keys are treated as unconfigured", () => {
  withEnv({ GROQ_API_KEY: undefined, LLM_API_KEY: undefined }, () => {
    assert.equal(isLlmConfigured(), false, "an absent key is unconfigured");
  });
  withEnv({ GROQ_API_KEY: "   ", LLM_API_KEY: undefined }, () => {
    assert.equal(isLlmConfigured(), false, "a blank key is unconfigured");
  });
  withEnv({ GROQ_API_KEY: "gsk_xxxxxxxx", LLM_API_KEY: undefined }, () => {
    assert.equal(isLlmConfigured(), false, "a documentation placeholder is unconfigured");
  });
  withEnv({ GROQ_API_KEY: "gsk_1a2b3c4d5e6f7g8h", LLM_API_KEY: undefined }, () => {
    assert.equal(isLlmConfigured(), true, "a real-looking key is configured");
  });
});

test("a missing key explains the fix instead of blaming the documents", () => {
  withEnv({ GROQ_API_KEY: undefined, LLM_API_KEY: undefined }, () => {
    const reason = describeAiUnavailable();
    assert.match(reason, /GROQ_API_KEY/);
    assert.match(reason, /retrieval/i, "the message should say retrieval still works");
  });
});

test("report fallback reasons never tell users to set a retired provider's key", () => {
  // Reports generated by pre-Groq builds embedded raw errors such as this one in
  // their disclaimer. If such an error ever resurfaces, the reason must point at
  // the current Groq setup instead of repeating stale GEMINI_API_KEY advice.
  const legacy = describeNarrativeFallbackReason(
    new Error("GEMINI_API_KEY is not configured. Please add a valid key to .env"),
  );
  assert.match(legacy, /GROQ_API_KEY/, "the fix must name the key that actually works now");
  assert.match(legacy, /Groq/);
  assert.doesNotMatch(legacy, /GEMINI_API_KEY|set GEMINI|add a valid key to \.env/i);
  assert.doesNotMatch(legacy, /^Error:/, "raw error prefixes must not leak into reports");
});

test("report fallback reasons explain a missing Groq key without raw error text", () => {
  withEnv({ GROQ_API_KEY: undefined, LLM_API_KEY: undefined }, () => {
    const reason = describeNarrativeFallbackReason(
      new Error("GROQ_API_KEY is not configured. Add your Groq API key to .env and restart the server."),
    );
    assert.match(reason, /GROQ_API_KEY/);
    assert.doesNotMatch(reason, /Error:/);
    assert.doesNotMatch(reason, /restart the server/i, "local-dev wording must not leak into reports");
  });
});

test("a provider failure keeps a compact detail and reassures that stored data is intact", () => {
  withEnv({ GROQ_API_KEY: "gsk_1a2b3c4d5e6f7g8h", LLM_API_KEY: undefined }, () => {
    const reason = describeNarrativeFallbackReason(new Error("LLM request failed (HTTP 429): rate limit exceeded"));
    assert.doesNotMatch(reason, /^Error:/);
    assert.match(reason, /429/);
    assert.match(reason, /not affected/i, "the report should say stored metrics/risks are unaffected");
    assert.doesNotMatch(reason, /GEMINI_API_KEY/);
  });
});

test("embeddings stay off unless a dedicated provider is fully configured", () => {
  const base = { EMBEDDING_BASE_URL: undefined, EMBEDDING_API_KEY: undefined, EMBEDDING_MODEL: undefined };
  withEnv(base, () => {
    assert.equal(isEmbeddingConfigured(), false);
    assert.equal(getEmbeddingConfig(), null);
  });
  // Groq has no embeddings API, so a Groq key alone must NOT enable semantic search.
  withEnv({ ...base, GROQ_API_KEY: "gsk_1a2b3c4d5e6f7g8h" }, () => {
    assert.equal(isEmbeddingConfigured(), false, "Groq alone cannot provide embeddings");
  });
  withEnv({ ...base, EMBEDDING_BASE_URL: "https://api.openai.com/v1", EMBEDDING_API_KEY: "sk-abc" }, () => {
    assert.equal(isEmbeddingConfigured(), false, "a model id is also required");
  });
  withEnv(
    {
      ...base,
      EMBEDDING_BASE_URL: "https://api.openai.com/v1/",
      EMBEDDING_API_KEY: "sk-abc",
      EMBEDDING_MODEL: "text-embedding-3-small",
    },
    () => {
      assert.equal(isEmbeddingConfigured(), true);
      assert.equal(getEmbeddingConfig()?.model, "text-embedding-3-small");
      assert.equal(getEmbeddingConfig()?.baseUrl, "https://api.openai.com/v1", "trailing slash is trimmed");
    },
  );
});

test("health status reports provider, unconfigured state, and records failures", () => {
  withEnv({ GROQ_API_KEY: undefined, LLM_API_KEY: undefined }, () => {
    const unconfigured = getAiStatus();
    assert.equal(unconfigured.configured, false);
    assert.equal(unconfigured.state, "unconfigured");
    assert.equal(unconfigured.lastError, null);
    assert.equal(unconfigured.provider, "Groq");
  });

  withEnv({ GROQ_API_KEY: "gsk_1a2b3c4d5e6f7g8h", LLM_API_KEY: undefined }, () => {
    recordAiFailure("HTTP 404 model decommissioned");
    const degraded = getAiStatus();
    assert.equal(degraded.configured, true);
    assert.equal(degraded.state, "degraded");
    assert.match(degraded.lastError || "", /404/);

    recordAiSuccess();
    assert.equal(getAiStatus().state, "ready", "a later success clears the degraded state");
    assert.equal(getAiStatus().lastError, null);
  });
});

test("JSON parsing tolerates fences and prose wrappers from chat models", () => {
  assert.deepEqual(parseJsonResponse('{"a":1}'), { a: 1 });
  assert.deepEqual(parseJsonResponse('```json\n{"a":1}\n```'), { a: 1 });
  assert.deepEqual(parseJsonResponse('Here is the JSON:\n{"a":1}\nHope that helps!'), { a: 1 });
  assert.deepEqual(parseJsonResponse('[{"a":1}]'), [{ a: 1 }]);
  assert.throws(() => parseJsonResponse("not json at all"), /not valid JSON/);
});