// Report Agent — compiles all insights into structured analyst-style reports
import { db } from "@/db";
import { analysisReports, financialMetrics, riskFlags, companies, documents, agentLogs } from "@/db/schema";
import { and, desc, eq, inArray, or } from "drizzle-orm";
import { DEFAULT_GEMINI_PRO_MODEL, generateWithGemini } from "./gemini";

export async function generateAnalysisReport(
  reportId: string,
  sessionId: string,
  userId: string,
  companyIds: string[],
  additionalContext?: string
): Promise<void> {
  const start = Date.now();

  await db.insert(agentLogs).values({
    sessionId,
    agentName: "Report Agent",
    action: "Starting report generation",
    status: "running",
    details: "Compiling financial analysis report...",
  });

  try {
    // Gather all data
    const companiesData = await db
      .select()
      .from(companies)
      .where(inArray(companies.id, companyIds));

    const metricsData = await db
      .select()
      .from(financialMetrics)
      .innerJoin(documents, eq(financialMetrics.documentId, documents.id))
      .where(and(
        inArray(financialMetrics.companyId, companyIds),
        or(eq(documents.userId, userId), eq(documents.isSeeded, true)),
      ))
      .orderBy(desc(financialMetrics.fiscalYear), desc(financialMetrics.extractedAt));

    const risksData = await db
      .select()
      .from(riskFlags)
      .innerJoin(documents, eq(riskFlags.documentId, documents.id))
      .where(and(
        inArray(riskFlags.companyId, companyIds),
        or(eq(documents.userId, userId), eq(documents.isSeeded, true)),
      ));

    // Build comprehensive context
    const companyProfiles = companiesData.map((co) => {
      const metrics = metricsData.map((row) => row.financial_metrics).find((m) => m.companyId === co.id);
      const risks = risksData.map((row) => row.risk_flags).filter((r) => r.companyId === co.id);

      return {
        company: `${co.name} (${co.ticker || "N/A"})`,
        sector: co.sector,
        metrics,
        risks: risks.map((r) => ({
          type: r.riskType,
          severity: r.severity,
          title: r.title,
          description: r.description,
        })),
      };
    });

    const reportPrompt = `You are a senior equity research analyst writing a professional financial research report.

Based on the following company data, write a comprehensive analyst-style report:

${JSON.stringify(companyProfiles, null, 2)}

${additionalContext ? `Additional context: ${additionalContext}` : ""}

Write the report in the following structure:

# EXECUTIVE SUMMARY
[2-3 paragraph overview of key findings]

# COMPANY PROFILES
[Brief profile for each company]

# FINANCIAL PERFORMANCE ANALYSIS
## Revenue & Growth
[Analysis with specific numbers]
## Profitability
[Margins analysis]
## Balance Sheet Strength
[Liquidity and leverage]
## Cash Flow Quality
[Cash generation analysis]

# RISK ANALYSIS
[Detailed risk assessment for each company]

# COMPETITIVE BENCHMARKING
[Comparative analysis if multiple companies]

# KEY INVESTMENT CONSIDERATIONS
[3-5 bullet points per company]

# ANALYST RECOMMENDATIONS
[Clear buy/hold/sell recommendation with rationale]

# DISCLAIMER
This report is generated by AI based solely on provided document data and should not be considered as investment advice.

Write in professional analyst prose. Be specific with numbers. Cite data directly.`;

    let fullReport: string;
    try {
      fullReport = await generateWithGemini(reportPrompt, undefined, DEFAULT_GEMINI_PRO_MODEL);
    } catch (error) {
      fullReport = createLocalReport(companyProfiles, String(error));
    }

    // Extract executive summary (first section)
    const execSummaryMatch = fullReport.match(/# EXECUTIVE SUMMARY\n([\s\S]*?)(?=\n#)/);
    const executiveSummary = execSummaryMatch ? execSummaryMatch[1].trim() : fullReport.slice(0, 500);

    // Extract recommendations
    const recommendations = companiesData.map((co) => {
      const buyMatch = fullReport.match(new RegExp(`(?:BUY|HOLD|SELL|OUTPERFORM|UNDERPERFORM).*${co.name}`, "i"));
      return buyMatch ? buyMatch[0] : `Review ${co.name} position based on current metrics`;
    });

    // Update report in DB
    await db
      .update(analysisReports)
      .set({
        executiveSummary,
        fullReportContent: fullReport,
        recommendations,
        companies: companiesData.map((co) => co.name),
        keyFindings: {
          totalCompanies: companiesData.length,
          totalRisks: risksData.length,
          criticalRisks: risksData.filter((r) => r.risk_flags.severity === "critical").length,
        },
        riskSummary: {
          byCompany: companiesData.map((co) => ({
            company: co.name,
            risks: risksData.filter((r) => r.documents.companyId === co.id).length,
          })),
        },
        status: "completed",
        updatedAt: new Date(),
      })
      .where(eq(analysisReports.id, reportId));

    await db.insert(agentLogs).values({
      sessionId,
      agentName: "Report Agent",
      action: "Report generation complete",
      status: "completed",
      details: `Generated ${fullReport.length} character report`,
      duration: Date.now() - start,
    });
  } catch (error) {
    await db
      .update(analysisReports)
      .set({ status: "failed", updatedAt: new Date() })
      .where(eq(analysisReports.id, reportId));

    await db.insert(agentLogs).values({
      sessionId,
      agentName: "Report Agent",
      action: "Report generation failed",
      status: "failed",
      details: String(error),
      duration: Date.now() - start,
    });
    throw error;
  }
}

type LocalReportProfile = {
  company: string;
  sector: string | null;
  metrics: typeof financialMetrics.$inferSelect | undefined;
  risks: Array<{
    type: string;
    severity: string;
    title: string;
    description: string;
  }>;
};

function createLocalReport(profiles: LocalReportProfile[], reason: string): string {
  const companySections = profiles.map((profile) => {
    const metrics = profile.metrics;
    const risks = profile.risks.length > 0
      ? profile.risks.map((risk) => `- ${risk.severity}: ${risk.title} (${risk.type})`).join("\n")
      : "- No stored risk flags were found for the selected documents.";

    return `## ${profile.company}
Sector: ${profile.sector || "Not provided"}
Revenue: ${metrics?.revenue ?? "N/A"} million
Revenue growth: ${metrics?.revenueGrowth ?? "N/A"}
Gross margin: ${metrics?.grossMargin ?? "N/A"}
Operating margin: ${metrics?.operatingMargin ?? "N/A"}
Net margin: ${metrics?.netMargin ?? "N/A"}
Current ratio: ${metrics?.currentRatio ?? "N/A"}
Debt-to-equity: ${metrics?.debtToEquity ?? "N/A"}
ROE: ${metrics?.roe ?? "N/A"}
Free cash flow: ${metrics?.freeCashFlow ?? "N/A"} million

Risks:
${risks}`;
  }).join("\n\n");

  return `# EXECUTIVE SUMMARY
This report is grounded in metrics and risk flags extracted from the selected uploaded documents. Gemini was unavailable, so no unsupported external claims were added.

# COMPANY PROFILES
${companySections}

# FINANCIAL PERFORMANCE ANALYSIS
The values below are reported exactly as extracted from the selected documents. N/A means the metric was not found or could not be extracted.

# RISK ANALYSIS
${companySections}

# ANALYST RECOMMENDATIONS
- Verify all N/A values against the original uploaded reports.
- Compare companies only when fiscal periods and units are comparable.
- Review every listed risk against its source document before making a decision.

# DISCLAIMER
This local report was generated from uploaded document data only. AI provider detail was unavailable (${reason}). It is informational and not investment advice.`;
}
